use anyhow::{anyhow, Result};
use chardetng::EncodingDetector;
use encoding_rs::{GB18030, UTF_16BE, UTF_16LE, UTF_8};
use image::codecs::jpeg::JpegEncoder;
use image::codecs::png::{CompressionType, FilterType, PngEncoder};
use image::ImageEncoder;
use serde::{Deserialize, Serialize};
use std::io::{Cursor, Write};
use zip::write::FileOptions;

const UTF8_TEXT_EXTENSIONS: &[&str] = &["json", "js", "ink"];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputFile {
    pub path: String,
    pub data: Vec<u8>,
}

impl InputFile {
    pub fn new(path: impl Into<String>, data: impl Into<Vec<u8>>) -> Self {
        Self {
            path: path.into(),
            data: data.into(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct OptimizeOptions {
    pub level: u8,
    pub json: bool,
    pub png: bool,
    pub jpeg: bool,
}

impl Default for OptimizeOptions {
    fn default() -> Self {
        Self {
            level: 2,
            json: true,
            png: true,
            jpeg: true,
        }
    }
}

#[derive(Clone)]
pub struct PackOptions<'a> {
    pub build_id: String,
    pub engine: String,
    pub optimize: Option<OptimizeOptions>,
    pub signing_key: Option<&'a aix::crypto::PrivateKey>,
}

impl<'a> PackOptions<'a> {
    pub fn new(build_id: impl Into<String>) -> Self {
        Self {
            build_id: build_id.into(),
            engine: "*".into(),
            optimize: None,
            signing_key: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum OptimizeStatus {
    Optimized,
    Unchanged,
    Skipped,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileOptimizeReport {
    pub path: String,
    pub status: OptimizeStatus,
    pub original_size: u64,
    pub output_size: u64,
    pub saved_bytes: u64,
    pub converted_to_utf8: bool,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OptimizeReport {
    pub files: Vec<FileOptimizeReport>,
    pub original_size: u64,
    pub output_size: u64,
    pub saved_bytes: u64,
}

#[derive(Debug)]
pub struct PackOutput {
    pub data: Vec<u8>,
    pub report: OptimizeReport,
}

#[derive(Debug)]
struct PreparedFile {
    data: Vec<u8>,
    converted_to_utf8: bool,
    optimized: bool,
    supported: bool,
}

pub fn pack(files: Vec<InputFile>, options: PackOptions<'_>) -> Result<PackOutput> {
    if options.build_id.is_empty() {
        return Err(anyhow!("build_id must not be empty"));
    }
    if files.iter().any(|file| file.path == "VERSION") {
        return Err(anyhow!("VERSION is generated by the packer"));
    }
    aix::crypto::validate_engine_range(&options.engine)
        .map_err(|error| anyhow!("invalid engine range: {}", error))?;

    let mut entries = Vec::with_capacity(files.len() + 1);
    entries.push(InputFile::new("VERSION", options.build_id.into_bytes()));
    entries.extend(files);
    pack_entries(
        entries,
        options.optimize.as_ref(),
        &options.engine,
        options.signing_key,
    )
}

pub fn optimize_package(data: &[u8], options: &OptimizeOptions) -> Result<PackOutput> {
    let reader = aix::AixReader::new(data.to_vec())?;
    let engine = reader
        .get_manifest()?
        .map(|manifest| manifest.engine)
        .unwrap_or_else(|| "*".into());
    let mut entries = Vec::with_capacity(reader.list().len());
    for entry in reader.list() {
        if entry.name.ends_with('/') || entry.name.starts_with("META-INF/aix/") {
            continue;
        }
        entries.push(InputFile::new(&entry.name, reader.read_file(&entry.name)?));
    }
    pack_entries(entries, Some(options), &engine, None)
}

fn pack_entries(
    mut files: Vec<InputFile>,
    optimize: Option<&OptimizeOptions>,
    engine: &str,
    signing_key: Option<&aix::crypto::PrivateKey>,
) -> Result<PackOutput> {
    files.sort_by(|a, b| a.path.as_bytes().cmp(b.path.as_bytes()));
    validate_paths(&files)?;

    let mut report = OptimizeReport::default();
    let mut prepared_files = Vec::with_capacity(files.len() + 3);

    for file in files {
        let original_size = file.data.len() as u64;
        let prepared = prepare_file(&file.path, file.data, optimize)?;
        let output_size = prepared.data.len() as u64;
        let saved_bytes = original_size.saturating_sub(output_size);
        report.original_size += original_size;
        report.output_size += output_size;
        report.saved_bytes += saved_bytes;
        report.files.push(FileOptimizeReport {
            path: file.path.clone(),
            status: if prepared.optimized {
                OptimizeStatus::Optimized
            } else if prepared.supported {
                OptimizeStatus::Unchanged
            } else {
                OptimizeStatus::Skipped
            },
            original_size,
            output_size,
            saved_bytes,
            converted_to_utf8: prepared.converted_to_utf8,
        });

        prepared_files.push(InputFile::new(file.path, prepared.data));
    }

    let manifest = build_manifest(&prepared_files, engine, signing_key);
    let manifest_data = serde_json::to_vec(&manifest)?;
    if let Some(key) = signing_key {
        let signature = key.sign(b"package-manifest", &manifest_data);
        prepared_files.push(InputFile::new(
            aix::crypto::SIGNATURE_PATH,
            signature.to_bytes(),
        ));
        prepared_files.push(InputFile::new(
            aix::crypto::PUBLIC_KEY_PATH,
            key.public_key().to_bytes(),
        ));
    }
    prepared_files.push(InputFile::new(aix::crypto::MANIFEST_PATH, manifest_data));
    prepared_files.sort_by(|a, b| a.path.as_bytes().cmp(b.path.as_bytes()));

    let cursor = Cursor::new(Vec::new());
    let mut zip = zip::ZipWriter::new(cursor);
    let file_options = FileOptions::default()
        .compression_method(zip::CompressionMethod::Stored)
        .unix_permissions(0o644);
    for file in prepared_files {
        zip.start_file(file.path, file_options)?;
        zip.write_all(&file.data)?;
    }

    Ok(PackOutput {
        data: zip.finish()?.into_inner(),
        report,
    })
}

fn build_manifest(
    files: &[InputFile],
    engine: &str,
    signing_key: Option<&aix::crypto::PrivateKey>,
) -> aix::crypto::PackageManifest {
    let mut entries = Vec::with_capacity(files.len());
    let mut version = String::new();
    for file in files {
        if file.path == "VERSION" {
            version = String::from_utf8_lossy(&file.data).into_owned();
        }
        let digest = aix::crypto::sha256(&file.data);
        entries.push(aix::crypto::ManifestEntry {
            path: file.path.clone(),
            size: file.data.len() as u64,
            sha256: digest,
        });
    }
    let package_id = aix::crypto::calculate_package_id(&entries);
    aix::crypto::PackageManifest {
        format: "aix".into(),
        version,
        engine: engine.into(),
        algorithm: "ed25519".into(),
        digest: "sha256".into(),
        key_id: signing_key
            .map(|key| key.public_key().key_id())
            .unwrap_or_default(),
        package_id,
        entries,
    }
}

fn validate_paths(files: &[InputFile]) -> Result<()> {
    let mut previous: Option<&str> = None;
    for file in files {
        let path = file.path.as_str();
        if path.is_empty()
            || path.starts_with('/')
            || path.contains('\\')
            || path
                .split('/')
                .any(|part| part.is_empty() || part == "." || part == "..")
        {
            return Err(anyhow!("invalid package path: {}", path));
        }
        if previous == Some(path) {
            return Err(anyhow!("duplicate package path: {}", path));
        }
        previous = Some(path);
    }
    Ok(())
}

fn prepare_file(
    path: &str,
    data: Vec<u8>,
    optimize: Option<&OptimizeOptions>,
) -> Result<PreparedFile> {
    let extension = path
        .rsplit_once('.')
        .map(|(_, ext)| ext)
        .unwrap_or("")
        .to_ascii_lowercase();
    let enabled = optimize.is_some();

    if extension == "json" {
        return prepare_json(path, &data, optimize.is_some_and(|options| options.json));
    }

    if UTF8_TEXT_EXTENSIONS.contains(&extension.as_str()) {
        let (utf8, converted) = normalize_text_to_utf8(path, &data)?;
        return Ok(PreparedFile {
            data: utf8,
            converted_to_utf8: converted,
            optimized: false,
            supported: enabled,
        });
    }

    match (extension.as_str(), optimize) {
        ("png", Some(options)) if options.png => {
            let candidate = optimize_png(&data, options.level)?;
            Ok(smaller_image(data, candidate))
        }
        ("jpg" | "jpeg", Some(options)) if options.jpeg => {
            let candidate = optimize_jpeg(&data, options.level)?;
            Ok(smaller_image(data, candidate))
        }
        _ => Ok(PreparedFile {
            data,
            converted_to_utf8: false,
            optimized: false,
            supported: false,
        }),
    }
}

fn smaller_image(original: Vec<u8>, candidate: Vec<u8>) -> PreparedFile {
    let optimized = candidate.len() < original.len();
    PreparedFile {
        data: if optimized { candidate } else { original },
        converted_to_utf8: false,
        optimized,
        supported: true,
    }
}

fn prepare_json(path: &str, data: &[u8], optimize: bool) -> Result<PreparedFile> {
    let (utf8, converted) = normalize_text_to_utf8(path, data)?;
    let value: serde_json::Value = serde_json::from_slice(&utf8)
        .map_err(|error| anyhow!("Invalid JSON in {}: {}", path, error))?;
    let candidate = if optimize {
        serde_json::to_vec(&value)?
    } else {
        utf8.clone()
    };
    let optimized = optimize && candidate.len() < utf8.len();
    Ok(PreparedFile {
        data: if optimized { candidate } else { utf8 },
        converted_to_utf8: converted,
        optimized,
        supported: true,
    })
}

fn optimize_png(data: &[u8], level: u8) -> Result<Vec<u8>> {
    let image = image::load_from_memory_with_format(data, image::ImageFormat::Png)?;
    let compression = match level {
        1 => CompressionType::Fast,
        3 => CompressionType::Best,
        _ => CompressionType::Default,
    };
    let mut output = Vec::new();
    PngEncoder::new_with_quality(&mut output, compression, FilterType::Adaptive).write_image(
        image.as_bytes(),
        image.width(),
        image.height(),
        image.color().into(),
    )?;
    Ok(output)
}

fn optimize_jpeg(data: &[u8], level: u8) -> Result<Vec<u8>> {
    let image = image::load_from_memory_with_format(data, image::ImageFormat::Jpeg)?;
    let quality = match level {
        1 => 90,
        3 => 75,
        _ => 82,
    };
    let mut output = Vec::new();
    JpegEncoder::new_with_quality(&mut output, quality).encode_image(&image)?;
    Ok(output)
}

fn normalize_text_to_utf8(path: &str, data: &[u8]) -> Result<(Vec<u8>, bool)> {
    if let Some(content) = data.strip_prefix(&[0xEF, 0xBB, 0xBF]) {
        return std::str::from_utf8(content)
            .map(|_| (content.to_vec(), true))
            .map_err(|_| anyhow!("Failed to decode {} as UTF-8", path));
    }
    if let Some(content) = data.strip_prefix(&[0xFF, 0xFE]) {
        return decode(path, content, UTF_16LE);
    }
    if let Some(content) = data.strip_prefix(&[0xFE, 0xFF]) {
        return decode(path, content, UTF_16BE);
    }
    if std::str::from_utf8(data).is_ok() {
        return Ok((data.to_vec(), false));
    }

    let (decoded, _, errors) = GB18030.decode(data);
    if !errors {
        return Ok((decoded.into_owned().into_bytes(), true));
    }

    let mut detector = EncodingDetector::new();
    detector.feed(data, true);
    let encoding = detector.guess(None, true);
    if encoding == UTF_8 {
        return Err(anyhow!("Failed to decode {} as UTF-8", path));
    }
    decode(path, data, encoding)
}

fn decode(
    path: &str,
    data: &[u8],
    encoding: &'static encoding_rs::Encoding,
) -> Result<(Vec<u8>, bool)> {
    let (decoded, _, errors) = encoding.decode(data);
    if errors {
        return Err(anyhow!(
            "Failed to convert {} from {} to UTF-8",
            path,
            encoding.name()
        ));
    }
    Ok((decoded.into_owned().into_bytes(), true))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packs_and_reads_an_artifact() {
        let output = pack(
            vec![InputFile::new("app.json", br#"{ "pages": [] }"#)],
            PackOptions {
                build_id: "test-build".into(),
                engine: "^0.14.0".into(),
                optimize: Some(OptimizeOptions::default()),
                signing_key: None,
            },
        )
        .unwrap();
        let reader = aix::AixReader::new(output.data).unwrap();
        assert_eq!(reader.get_version().as_deref(), Some("test-build"));
        assert_eq!(reader.read_file("app.json").unwrap(), br#"{"pages":[]}"#);
        assert!(reader.supports_engine("0.14.9").unwrap());
        assert!(!reader.supports_engine("0.15.0").unwrap());
    }

    #[test]
    fn rejects_unsafe_paths() {
        let error = pack(
            vec![InputFile::new("../app.json", b"{}")],
            PackOptions {
                build_id: "test-build".into(),
                engine: "*".into(),
                optimize: None,
                signing_key: None,
            },
        )
        .unwrap_err();
        assert!(error.to_string().contains("invalid package path"));
    }

    #[test]
    fn signs_and_verifies_an_artifact() {
        let key = aix::crypto::PrivateKey::from_seed([9; 32]);
        let output = pack(
            vec![InputFile::new("app.json", br#"{"pages":[]}"#)],
            PackOptions {
                build_id: "signed-build".into(),
                engine: ">=0.14.0".into(),
                optimize: None,
                signing_key: Some(&key),
            },
        )
        .unwrap();
        let reader = aix::AixReader::new(output.data).unwrap();
        let report = reader.verify_signature(&key.public_key()).unwrap();
        assert_eq!(report.version, "signed-build");
        assert_eq!(report.engine, ">=0.14.0");
        assert_eq!(report.entry_count, 2);
    }

    #[test]
    fn strips_utf8_bom_before_parsing_json() {
        let mut data = vec![0xEF, 0xBB, 0xBF];
        data.extend_from_slice(br#"{"pages":[]}"#);

        let prepared = prepare_json("app.json", &data, false).unwrap();

        assert_eq!(prepared.data, br#"{"pages":[]}"#);
        assert!(prepared.converted_to_utf8);
    }

    #[test]
    fn strips_utf16_bom_during_conversion() {
        let mut data = vec![0xFF, 0xFE];
        for unit in "const ready = true;".encode_utf16() {
            data.extend_from_slice(&unit.to_le_bytes());
        }

        let (normalized, converted) = normalize_text_to_utf8("app.js", &data).unwrap();

        assert_eq!(normalized, b"const ready = true;");
        assert!(converted);
    }
}
